# Generated by Django 2.0.5 on 2019-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('doj', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='user_profile/')),
            ],
        ),
    ]
