# Generated by Django 2.0.5 on 2019-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='lname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
