# Generated by Django 2.0.5 on 2019-12-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('admin', '0002_complains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('p_status', models.CharField(max_length=20)),
                ('bid_price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(upload_to='products/')),
                ('image3', models.ImageField(upload_to='products/')),
                ('disc', models.TextField(max_length=3000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserRegister')),
            ],
        ),
    ]
