# Generated by Django 2.0.5 on 2019-12-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('admin', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitTable',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxBidTable',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('max_amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='maxbidtable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Products'),
        ),
        migrations.AddField(
            model_name='maxbidtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserRegister'),
        ),
        migrations.AddField(
            model_name='bittable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Products'),
        ),
        migrations.AddField(
            model_name='bittable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserRegister'),
        ),
    ]
