# Generated by Django 2.0.5 on 2019-12-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('admin', '0004_auto_20191218_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_status', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserRegister')),
            ],
        ),
    ]
