# Generated by Django 2.0.5 on 2019-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
