# Generated by Django 2.0.5 on 2019-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20191226_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
