# Generated by Django 2.0.5 on 2020-01-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_order_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
